config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :hobbies

  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/hobby.rb
class Hobby < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user  
    has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts

  has_many :posts, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  #mount_uploader :image, ImageUploader
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.build(comment_params) #buildを使い、contentとpost_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
    def index
    end
  
    def new
      @hobby = Hobby.new
    end
  
    def show
      @hobby = Hobby.find_by(id: params[:id])
    end
  
    def create
      @hobby = Hobby.new(hobby_params)
      params[:hobby][:question] ? @hobby.question = params[:hobby][:question].join("") : false
      if @hobby.save
          flash[:notice] = "診断が完了しました"
          redirect_to hobby_path(@hobby.id)
      else
          redirect_to :action => "new"
      end
    end
  
  private
    def hobby_params
        params.require(:hobby).permit(:id, question: [])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id]) #user_idとpost_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
    def index
        @posts = Post.all
    end

    def new
        @post = Post.new
    end
    
    def create
      post = Post.new(post_params)
      if post.save!
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
    end

    def create
      post = Post.new(post_params)
  
      post.user_id = current_user.id  #追記
  
      if post.save
        redirect_to action: "index"
      else
        redirect_to action: "new"
      end
    end

    def show
      @post = Post.find(params[:id])
      @comments = @post.comments
      @comment = Comment.new
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      post = Post.find(params[:id])
      if post.update(post_params)
        redirect_to :action => "show", :id => post.id
      else
        redirect_to :action => "new"
      end
    end
    
    def destroy
      post = Post.find(params[:id])
      post.destroy
      redirect_to action: :index
    end
    private
    def post_params
      params.require(:post).permit(:content, :image, :user_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hobbies/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>趣味診断スタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>

        <div class="shumishinndannsuru">
                <h1 class="headline">
                <a>趣味診断をする</a>
                </h1>
                <ul class="nav-list">
                    <li class="nav-list-item">about hobby</li>
                </ul>
        </div>

        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_hobby_path, class: "button" %>
        </div>
    </body>

app/views/hobbies/new.html.erb
<%= form_for(@hobby, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="container-sindan">
        <div class="row">

            <div class="col-12">
                <p>Question1. 体を動かすことが好きですか？</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>好きだ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>嫌いだ</p>
            </div>
        </div>

        <div class="raw2">
            <div class="col-12">
                <p>Question2. 考えることが好きですか？</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>好きだ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>嫌いだ</p>
            </div>
        </div>

        <div class="raw3">
            <div class="col-12">
                <p>Question3. 趣味に使うお金はどのくらいありますか？</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>ある</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>ない</p>
            </div>
        </div>

        <div class="raw4">
            <div class="col-12">
                <p>Question4. 趣味に使う時間はどのくらいありますか？</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>めちゃくちゃある</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>そこそこある</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "3", nil %>ほとんどない</p>
            </div>
        </div>
    </div>
  
        <%= f.submit "診断結果へ"  , class: "mzk-button"%>
    
<% end %>

app/views/hobbies/show.html.erb
<div class="intoro">
<h5>診断結果</h5>
<p>あなたにおすすめの趣味は…</p>
</div>
<div class="post-container">
<div class="post">
    <% if @hobby.question == "1212" %>
    <h3>スポーツ</h3>
    <p>アクティブなあなたにおすすめ！！！！！！！</p>
    <p>球技では野球・サッカーがおすすめ！！！！！！</p>
    <p>初心者はランニング筋トレがおすすめ！！！！！！！</p>

    <% elsif @hobby.question == "1122" %>
    <h3>スポーツ観戦</h3>
    <p>アクティブなあなたにおすすめ！！！！！！！</p>
    <p>リラックス効果があるかも！？</p>

    <% elsif @hobby.question == "2123" %>
    <h3>料理</h3>
    <p>インドアで考えたいあなたにおすすめ！！！！！！</p>
    <p>ストレスを緩和してくれる効果があるかも！？</p>

    <% elsif @hobby.question == "1111" %>
    <h3>キャンプ</h3>
    <p>休日の1日を長く、有意義に過ごせる！！！！</p>
    <p>気持ちを落ち着かせてくれる</p>

    <% elsif @hobby.question == "1213" %>
    <h3>アウトドアレジャー</h3>
    <p>アクティブで思考力があるあなたにおすすめ！！！！</p>
    <p>自然の中でリラックスできる！</p>

    <% elsif @hobby.question == "1112" %>
    <h3>ショッピング</h3>
    <p>リフレッシュになる</p>
    <p>購入によりドーパミンが上昇し、快楽が感じるも、依存には注意！！！</p>

    <% elsif @hobby.question == "2122" %>
    <h3>ゲーム</h3>
    <p>最近ではプロになる人も！？</p>
    <p>万人受けしやすい趣味</p>

    <% elsif @hobby.question == "2111" %>
    <h3>資格</h3>
    <p>自分を高めることができる！！！！</p>
    <p>時間があれば司法試験・公認会計士を目指そう</p>

    <% elsif @hobby.question == "1123" %>
    <h3>フォトグラフィー</h3>
    <p>最近ではスマホの性能が上がって誰でもできる趣味に！！！！！</p>
    <p>映えスポットをめぐるのもいいかも！！！！！</p>

    <% elsif @hobby.question == "2112" %>
    <h3>投資</h3>
    <p>今の財産を大きく増やせるチャンス！！！！！</p>
    <p>ただし、ハイリスク・ハイリターンなので注意！！！！！</p>

    <% elsif @hobby.question == "2223" %>
    <h3>音楽を聴く</h3>
    <p>音楽を聞くことで、心の健康にいい！！！！！</p>
    <p>好きなアーティストを探すためにフェスに参加するのもあり！！！！！</p>

    <% elsif @hobby.question == "1211" %>
    <h3>楽器を弾く</h3>
    <p>楽器を弾くことは、脳を活性化させる！！！！！！</p>
    <p>和楽器に手を出すのもあり！！！！</p>

    <% elsif @hobby.question == "1221" %>
    <h3>旅行</h3>
    <p>旅行にいくことで、自分の知見を深めることができる！！！</p>
    <p>まずは国内旅行や隣県に行くのから初めて見てはどう？</p>

    <% elsif @hobby.question == "2213" %>
    <h3>植物栽培</h3>
    <p>風水的にもおすすめ！！！！</p>
    <p>サボテンはお世話が少ないから、おすすめ！！！</p>

    <% elsif @hobby.question == "2222" %>
    <h3>手芸</h3>
    <p>モノができることで成果がでて、モチベ↑↑</p>
    <p>ニードルフェルトが手軽でおすすめ！！！</p>

    <% elsif @hobby.question == "2121" %>
    <h3>プログラミング</h3>
    <p>最近では価値が向上し、大学生が一番やるべき趣味に！！！！</p>
    <p></p>
    <p></p>

    <% elsif @hobby.question == "2212" %>
    <h3>コレクション</h3>
    <p>高価なコレクションは資産にもなる！！！</p>
    <p>時計や靴、カードゲームの収集もあり！！！！</p>

    <% elsif @hobby.question == "1113" %>
    <h3>ファッション</h3>
    <p>着飾ることで、自分に自信がでる！！！！！</p>
    <p>単純にモテる！！！</p>

    <% elsif @hobby.question == "2221" %>
    <h3>絵を描く</h3>
    <p>画材は絵具から砂など幅広い（お手軽）！！！！！</p>
    <p>心を落ち着かせてくれる！！！！！</p>

    <% elsif @hobby.question == "1121" %>
    <h3>コレクション（アクティブ系）</h3>
    <p>御朱印集め、ご当地マンホールを撮ることがおすすめ！！！！</p>
    <p>土地ごとに違いが出て、オモシロイ！！！！！</p>

    <% elsif @hobby.question == "2113" %>
    <h3>芸術鑑賞</h3>
    <p>絵画や映画をみることで、感受性を豊かにできる</p>
    <p>自分の中で分析することにチャレンジ！！！！！！</p>

    <% elsif @hobby.question == "2211" %>
    <h3>コレクション</h3>
    <p>高価なコレクションは資産にもなる！！！</p>
    <p>時計や靴、カードゲームの収集もあり！！！！</p>

    <% elsif @hobby.question == "1223" %>
    <h3>ランニング</h3>
    <p>運動不足の</p>
    <p>モチベーションのために、有名なランニングシューズを買うのもいいかも</p>

    <% elsif @hobby.question == "1222" %>
    <h3>散歩</h3>
    <p>まずはこれから！！！！</p>
    <p>日常の細かい変化に気が付ける！！！！！</p>

    <% end %>

</div>

<div class="post-re">
    <%= link_to "投稿一覧に戻る", posts_path , class: "button"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shumitsuketa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/15b583374d.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <header>
  <div class="header-logooo">
      <div class="header-icon">
        <%= link_to image_tag("shumituketa.logo.png", size:"150x150"), posts_path %>
      </div>
      <div class="header-list">
        <h2>Anataの趣味を見つけ出し、シェアするサイト</h2>
        <h1>ShumitsuketA～しゅみつけタ～</h1>
      </div>
  </div>

    <div class="header-log">
      <ul>
        <% if user_signed_in? %>
        <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "p-button" %></li>
        <li><%= link_to "新規投稿へ", new_post_path , class: "button"%><li>
        <li><%= link_to "投稿一覧に戻る", posts_path ,  class: "button" %><li>
        <li><%= link_to '診断へ', hobbies_path ,  class: "button" %></li>
        <li><%= link_to "マイページへ", user_path(current_user.id) , class: "button"%></li>
        <% else %>
        <li><%= link_to "新規登録", new_user_registration_path , class: "button" %></li>
        <li><%= link_to "新規投稿へ", new_post_path , class: "button"%></i>
        <li><%= link_to "ログイン", new_user_session_path , class: "button" %></li>
        <li><%= link_to '診断へ', hobbies_path , class: "button" %></li>
        <li><%= link_to "投稿一覧に戻る", posts_path , class: "button" %><li>
        <% end %>
      </ul>
    </div>
 </header>
 <main>
  <%= yield %>
 </main>
</body>
 
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <% if user_signed_in?  %>
    <%= f.label :content %>
    <%= f.text_field :content, :size => 140 %> 
    <%= f.submit "編集する" %>
<% end %>
<% end %>

app/views/posts/index.html.erb
<h4></h4>
<div class="posts-ichiran">
  <h3>みんなの投稿一覧ページ</h3>
</div>

<div class="posts-container">

  <% @posts.each do |t| %>
    <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_post_path(t.id) , class: "button"%>
      <%= button_to "削除する", post_path(t.id), method: :delete , class: "mzk-button"%>
    <% end %> 
    <%= link_to '投稿詳細ページへ', post_path(t.id) , class: "button"%>
    <div class="post">
      <%= t.content %>
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.user.email %>
      <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= button_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
      <% else %>
      <i class="fas fa-heart"></i><%= t.likes.count %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1></h1>
<h3>新規投稿ページ</h3>
<%= form_for @post do |f| %>
    <div class="field">
    <%= f.label :コメントする  %>
    <%= f.text_area :content, :size => "30x2" %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "投稿する", class: "button" %>
<% end %>

<%= link_to "一覧に戻る", posts_path , class: "button"%>

app/views/posts/show.html.erb
<h1></h1>
<h3>post詳細</h3>
<div class="post">
  <p><%= @post.content %></p>
  <p><%= @post.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
        <%= button_to post_like_path(@post), method: :delete do %>
          <i class="fas fa-heart"></i><%= @post.likes.count %>
        <% end %>
      <% else %>
        <%= button_to post_likes_path(@post), method: :post do %>
          <i class="fas fa-heart"></i><%= @post.likes.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="fas fa-heart"></i><%= @post.likes.count %>
    <% end %>
    <% if user_signed_in? && current_user.id == @post.user_id %>
      <%= link_to "編集する", edit_post_path(@post.id) %>
    <% end %>
</div>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "post一覧に戻る", posts_path , class: "button"%>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<%= image_tag @user.image_url, size: "250x200" if @user.image? %>

<h2>ユーザーの投稿一覧</h2>
<% @user.posts.each do |t| %>
  <%= t.user.name %>
  <%= t.content %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_posts.each do |t| %>
  <%= t.user.name %>
  <%= t.content %>
<% end %>
<!-- ここまで-->

<%= link_to "   投稿一覧に戻る", posts_path %>